### ISSUE TITLE
Question about sampling process of "Sharing Matters for Generalization in Deep Metric Learning"

### ISSUE THREAD

**Issue by HeimingX** [MLforHealth/S2SD#2]
Dear authors,

Thanks for the serial awesome works on metric learning and the released code.

I am very interested in the idea of learning sharing features across classes in [1]. And I noticed that this work has been accpeted by TPAMI, Congratulations! 

The sharing features are obtained through constructing various class triplets in Sec. 3.2. But I have a question about the online sampling process: In sub-section "Online sampling of inter-class triplets t∗", the triplets sayed to be sampled based on analytical distance distribution, but I am curious that if 【both positive and negative samples are sampled based on the same distribution】or 【only negative samples are sampled based on the distance distribution and postive samples are randomly sampled】? 

PS：the question is raised in this reposince because I do not find the open-resouced code of [1], thanks.

[1] Sharing Matters for Generalization in Deep Metric Learning

**Comment by Confusezius** [comment]
Hi there!

Thanks for the kind words!
As you correctly noted, this is not the right repository (although you should definitely check it out, S2SD does wonders for generalization performance in DML!), however I'm happy to link you to https://github.com/Confusezius/ECCV2020_DiVA_MultiFeature_DML which is the de-facto extension of the TPAMI work and contains both code for inter-class triplet sampling as well as other orthogonal approaches to improve the generalizability of metric spaces!

Hope that helps!

**Comment by HeimingX** [comment]
Awesome! Thanks a lot~
